# Curated domain labels for channels the keyword lexicon misses or gets wrong.
# Keyed by exact channel title as returned by the API.
OVERRIDES = {
    # --- general education / explainer ---
    "CGP Grey": "general_education", "CGPGrey2": "general_education",
    "CGP Play": "general_education", "Wendover Productions": "general_education",
    "Half as Interesting": "general_education", "Tom Scott": "general_education",
    "Tom Scott plus": "general_education", "The Technical Difficulties": "comedy_sketch",
    "CrashCourse": "general_education", "Complexly": "general_education",
    "vlogbrothers": "general_education", "Hank Green": "general_education",
    "hankgames": "gaming", "John Green": "general_education",
    "exurb1a": "general_education", "Zogg from Betelgeuse": "general_education",
    "Answer in Progress": "general_education", "Phil Edwards": "general_education",
    "Trace Dominguez": "science", "Asianometry": "programming_tech",
    "RAINBOLT": "gaming", "RAINBOLT TWO": "gaming",
    "Atomic Frontier": "science", "The Good Stuff": "general_education",
    "Thought Café": "general_education", "How to Adult": "general_education",
    "Ze Frank": "comedy_sketch", "zefrankenfriends": "comedy_sketch",
    "WheezyWaiter": "vlog_personality", "AlwaysWheezy": "vlog_personality",
    "yourharto": "vlog_personality", "This is Dan Bell.": "video_essay_media",
    "Hello Internet": "podcast_actualplay", "Jordan Jonas": "nature_bio",
    # --- science / math ---
    "Vsauce": "science", "2veritasium": "science", "D!NG": "science",
    "Kurzgesagt – In a Nutshell": "science", "Nightshift – Kurzgesagt After Dark": "science",
    "minutephysics": "science", "MinuteEarth": "science", "Steve Mould": "science",
    "AlphaPhoenix": "science", "NileRed": "science", "NileBlue": "science",
    "Physics Girl": "science", "Fermilab": "science", "Sixty Symbols": "science",
    "DeepSkyVideos": "science", "Objectivity": "science", "Periodic Videos": "science",
    "nottinghamscience": "science", "BackstageScience": "science", "psyfile": "science",
    "Journey to the Microcosmos": "nature_bio", "thebrainscoop": "nature_bio",
    "Emily Graslie": "nature_bio", "BrainCraft": "science", "Quirkology": "science",
    "potholer54": "science", "styropyro": "science", "styro pyro 2": "science",
    "Explosions&Fire": "science", "The Thought Emporium": "science",
    "Scott Manley": "science", "Chubbyemu": "science", "sexplanations": "science",
    "PBS Eons": "nature_bio", "Animalogic": "nature_bio", "Bizarre Beasts": "nature_bio",
    "Ariel Waldman": "science", "BlackHoleCam": "science", "fyfluiddynamics": "science",
    "Mick West": "science", "Sciencium": "science", "Mike Likes Science": "science",
    "Living Science": "science", "Alexis Dahl": "science", "geothebio": "nature_bio",
    "Crime Pays But Botany Doesn't": "nature_bio", "Angela Collier ": "science",
    "3Blue1Brown": "math", "Grant Sanderson": "math", "Numberphile": "math",
    "Numberphile2": "math", "Mathologer": "math", "Stand-up Maths": "math",
    "Vihart": "math", "singingbanana": "math", "Think Twice": "math",
    "Welch Labs": "math", "Henry Segerman": "math", "PBS Infinite Series": "math",
    "Looking Glass Universe": "science", "ele VR": "math", "FLEB": "gaming",
    "xkcd's What If?": "general_education", "Ben Eater": "engineering_making",
    "Physics Videos by Eugene Khutoryansky": "science",
    # --- engineering / making ---
    "Mark Rober": "engineering_making", "Stuff Made Here": "engineering_making",
    "Stuff Made Here 2": "engineering_making", "Simone Giertz": "engineering_making",
    "colinfurze": "engineering_making", "I did a thing": "engineering_making",
    "Allen Pan": "engineering_making", "James Bruton": "engineering_making",
    "DIY Perks": "engineering_making", "Jeremy Fielding": "engineering_making",
    "Practical Engineering": "engineering_making", "engineerguy": "engineering_making",
    "ElectroBOOM": "engineering_making", "Boston Dynamics": "engineering_making",
    "abe's projects": "engineering_making", "kiwami japan": "engineering_making",
    "LightningOnDemand": "engineering_making", "yeti dynamics": "science",
    "Mattias Krantz": "music", "Inkbox": "engineering_making",
    "Greig Johnson Making": "engineering_making", "HeroTech": "engineering_making",
    "Scott Yu-Jan": "engineering_making", "Make With Miles": "engineering_making",
    "Engineer Bo": "engineering_making", "AngeTheGreat": "programming_tech",
    "Hedron Rockworks": "engineering_making", "ProjectsInFlight": "engineering_making",
    "Built World": "engineering_making", "The Slow Mo Guys": "science",
    "The Slow Mo Guys 2": "science", "Walt Disney Imagineering": "engineering_making",
    "iFixit": "programming_tech", "Framework": "programming_tech",
    "samy kamkar": "programming_tech", "stacksmashing": "programming_tech",
    "LockPickingLawyer": "engineering_making",
    # --- programming / consumer tech ---
    "Fireship": "programming_tech", "Beyond Fireship": "programming_tech",
    "Computerphile": "programming_tech", "sentdex": "programming_tech",
    "Sebastian Lague": "programming_tech", "Freya Holmér": "programming_tech",
    "CodeParade": "programming_tech", "CodeAesthetic": "programming_tech",
    "No Boilerplate": "programming_tech", "fasterthanlime": "programming_tech",
    "jdh": "programming_tech", "b001": "programming_tech", "typecraft": "programming_tech",
    "Nick Chapsas": "programming_tech", "dotnet": "programming_tech",
    "Dreams of Code": "programming_tech", "Nir Lichtman": "programming_tech",
    "Daniel Stenberg": "programming_tech", "Jeff Geerling": "programming_tech",
    "Kevin Fang": "programming_tech", "Jabrils": "programming_tech",
    "Jordan Harrod": "programming_tech", "f4mi": "programming_tech",
    "optozorax": "programming_tech", "Tom Delalande": "programming_tech",
    "Juxtopposed": "programming_tech", "TheHappieCat": "programming_tech",
    "Denis Shiryaev": "programming_tech", "Dave's Garage": "programming_tech",
    "Marques Brownlee": "programming_tech", "MrMobile [Michael Fisher]": "programming_tech",
    "MobileTechReview": "programming_tech", "Hardware Unboxed": "programming_tech",
    "Gamers Nexus": "programming_tech", "HDTVTest": "programming_tech",
    "DankPods": "programming_tech", "Technology Connections": "general_education",
    "Technology Connextras": "general_education", "Posy": "video_essay_media",
    "AustinSV": "programming_tech", "M Stem": "programming_tech",
    "Premature Abstraction": "programming_tech", "Recursion": "programming_tech",
    "About Clean Code": "programming_tech", "CodeOpinion": "programming_tech",
    "William": "programming_tech", "camwing": "programming_tech",
    "Damien Henry": "programming_tech", "David Achu": "programming_tech",
    "adumb": "programming_tech", "veselekov": "programming_tech",
    "Charles Clayton": "programming_tech", "Ed Andersen": "programming_tech",
    "GigaBoots Tech Lab": "programming_tech", "Micro": "programming_tech",
    # --- retro tech / hardware ---
    "LGR": "retro_tech", "Techmoan": "retro_tech", "VWestlife": "retro_tech",
    "Michael MJD": "retro_tech", "RetroRGB": "retro_tech",
    "Retro Game Corps": "retro_tech", "Macho Nacho Productions": "retro_tech",
    "Taki Udon": "retro_tech", "Taki II": "retro_tech", "Shank Mods": "retro_tech",
    "This Does Not Compute": "retro_tech", "Tech Tangents": "retro_tech",
    "Cathode Ray Dude - CRD": "retro_tech", "Cathode Ray Dude Gaiden": "retro_tech",
    "Modern Vintage Gamer": "retro_tech", "retromeister": "retro_tech",
    "VampierMSX": "retro_tech", "AllThingsOnePlace": "retro_tech",
    "Gaming Historian": "retro_tech", "ClassicGameJunkie": "retro_tech",
    "FixItMan78": "retro_tech", "Auto Focus": "retro_tech",
    "The Video Game History Foundation": "retro_tech",
    # --- gaming / speedrun / game analysis ---
    "Summoning Salt": "speedrun_glitch", "pannenkoek2012": "speedrun_glitch",
    "UncommentatedPannen": "speedrun_glitch", "Kaze Emanuar": "speedrun_glitch",
    "Bismuth": "speedrun_glitch", "EZScape": "speedrun_glitch",
    "Linkus7": "speedrun_glitch", "gymnast86": "speedrun_glitch",
    "cheese speedrunning": "speedrun_glitch", "CosmoSpeedruns": "speedrun_glitch",
    "Lance McDonald": "speedrun_glitch", "Zullie the Witch": "speedrun_glitch",
    "Boundary Break": "speedrun_glitch", "Gamechamp3000": "speedrun_glitch",
    "GingerOfOz": "speedrun_glitch", "Malleo": "speedrun_glitch",
    "PortalRunner": "speedrun_glitch", "AverageTreyVG": "speedrun_glitch",
    "Sean Seanson": "gaming", "Iron Pineapple": "gaming",
    "Ahoy": "game_design_analysis", "Game Maker's Toolkit": "game_design_analysis",
    "Design Doc": "game_design_analysis", "Errant Signal": "game_design_analysis",
    "Writing on Games": "game_design_analysis", "Daryl Talks Games": "game_design_analysis",
    "Matthewmatosis": "game_design_analysis", "Joseph Anderson": "game_design_analysis",
    "Super Bunnyhop": "game_design_analysis", "NakeyJakey": "game_design_analysis",
    "tim rogers": "game_design_analysis", "Action Button": "game_design_analysis",
    "Action Button Channel Two": "game_design_analysis",
    "Noah Caldwell-Gervais": "game_design_analysis",
    "Games As Literature": "game_design_analysis", "People Make Games": "game_design_analysis",
    "Core-A Gaming": "game_design_analysis", "Leon Massey": "game_design_analysis",
    "New Frame Plus": "game_design_analysis", "Turbo Button": "game_design_analysis",
    "Game Score Fanfare": "music", "Marshall McGee": "game_design_analysis",
    "Daryl Talks Games ": "game_design_analysis", "Super Eyepatch Wolf": "video_essay_media",
    "Digital Foundry": "gaming", "Polygon": "gaming", "Waypoint": "gaming",
    "Remap": "gaming", "BDGs VODs": "gaming", "brian david gilbert": "comedy_sketch",
    "Jon Bois": "wrestling_sports", "Secret Base": "wrestling_sports",
    "/noclip": "gaming", "Kerbal Space Program": "gaming", "Subnautica": "gaming",
    "Zachtronics": "gaming", "IcePickLodge": "gaming", "Pillow Castle": "gaming",
    "[mtbdesignworks {Miegakure, 4D Toys}]": "gaming", "William Chyr": "gaming",
    "Fallout 4: New Vegas": "gaming", "Earth's Special Forces": "gaming",
    "Zeria": "gaming", "Abnormal Mapping": "podcast_actualplay",
    "Barry Kramer": "gaming", "GamesWithHank": "gaming",
    "Gaming Historian ": "retro_tech", "minimme": "gaming",
    "oboeshoesgames": "gaming", "yahtzee19": "gaming",
    "HyperBitHero": "gaming", "Dev Detour": "gaming",
    "Speed Docs": "speedrun_glitch", "The Infinite Review": "video_essay_media",
    "Any Austin": "gaming", "2kliksphilip": "gaming",
    # --- video essays / film / media ---
    "Lindsay Ellis": "video_essay_media", "Vintage ChezLindsay": "video_essay_media",
    "hbomberguy": "video_essay_media", "Folding Ideas": "video_essay_media",
    "Jenny Nicholson": "video_essay_media", "Sarah Z": "video_essay_media",
    "Big Joel": "video_essay_media", "Jack Saint": "video_essay_media",
    "KyleKallgrenBHH": "video_essay_media", "Pop Culture Detective": "video_essay_media",
    "Now You See It": "video_essay_media", "Every Frame a Painting": "video_essay_media",
    "kaptainkristian": "video_essay_media", "Nerdwriter1": "video_essay_media",
    "Patrick (H) Willems": "video_essay_media", "RedLetterMedia": "video_essay_media",
    "FILM CRIT HULK": "video_essay_media",
    "Lessons from the Screenplay": "video_essay_media",
    "The Royal Ocean Film Society": "video_essay_media",
    "Beyond the Frame": "video_essay_media", "StrucciMovies": "video_essay_media",
    "Defunctland": "video_essay_media", "Defunctland After Dark": "video_essay_media",
    "Fredrik Knudsen": "video_essay_media", "Atrocity Guide": "video_essay_media",
    "Barely Sociable": "video_essay_media", "Quinton Reviews": "video_essay_media",
    "FilmJoy": "video_essay_media", "The Movie Rabbit Hole": "video_essay_media",
    "History Buffs": "video_essay_media", "Trekspertise": "video_essay_media",
    "Suede": "video_essay_media", "Suede's Pokémon Journey": "video_essay_media",
    "B- Mask": "video_essay_media", "BREADSWORD": "video_essay_media",
    "Jacob Geller": "video_essay_media", "Laura Crone": "video_essay_media",
    "Lady Emily": "video_essay_media", "Maritime Horrors": "video_essay_media",
    "MegaLag": "video_essay_media", "Misinformed": "video_essay_media",
    "Rabbit Hole": "video_essay_media", "vidthoughts": "video_essay_media",
    "bobvids": "video_essay_media", "Red Bard": "video_essay_media",
    "docfuture1": "video_essay_media", "Good Work": "video_essay_media",
    "Nathan Zed": "video_essay_media", "Princess Weekes": "video_essay_media",
    "Intelexual Media": "video_essay_media", "Mike Rugnetta": "video_essay_media",
    "PBS Idea Channel": "video_essay_media", "Soph's Notes": "video_essay_media",
    "Weebservations": "video_essay_media", "The Pedantic Romantic": "video_essay_media",
    "The Canipa Effect": "video_essay_media", "Get In The Robot": "video_essay_media",
    "Justin Sevakis": "video_essay_media", "Umbrella Terms": "video_essay_media",
    "Quorators": "video_essay_media", "allthequestions": "video_essay_media",
    "Dan Golding - Video Essays": "video_essay_media", "HeavyEyed": "video_essay_media",
    "Tantacrul": "music", "12tone": "music", "Adam Neely": "music",
    "Alex Moukala Music": "music", "Benn Jordan": "music",
    "kavan": "video_essay_media", "Novacanoo": "video_essay_media",
    "eurothug4000": "gaming", "The Back Focus": "video_essay_media",
    "Aidin Robbins": "video_essay_media", "greysfavs": "video_essay_media",
    "Stephanie Sammann": "general_education", "The Overview Effekt": "video_essay_media",
    "Works By Design": "video_essay_media", "Design Theory": "video_essay_media",
    "Worlds In Motion": "video_essay_media", "Beyond the Frame ": "video_essay_media",
    "Auralnauts": "comedy_sketch", "Peter Jackson": "video_essay_media",
    "The Studio": "video_essay_media", "Bright Sun Films": "video_essay_media",
    "Bright Sun Travels": "video_essay_media",
    # --- politics / philosophy / society ---
    "ContraPoints": "politics_society", "ContraPointsLive": "politics_society",
    "Philosophy Tube": "politics_society", "Shaun": "politics_society",
    "Innuendo Studios": "politics_society", "Zoe Baker": "politics_society",
    "F.D Signifier": "politics_society", "T1J": "politics_society",
    "Kat Blaque": "politics_society", "Angie Speaks": "politics_society",
    "Jonas Čeika - CCK Philosophy": "politics_society", "Mia Mulder": "politics_society",
    "Carlos Maza": "politics_society", "Citations Needed": "politics_society",
    "donoteat01": "urbanism_transit", "the bread is rising": "politics_society",
    "Renegade Cut": "politics_society", "Feminist Frequency": "politics_society",
    "Zohran Mamdani for NYC": "politics_society", "Adam Conover": "politics_society",
    "Eldena Doubleca5t": "politics_society", "YourCoolUncleMarisa": "politics_society",
    "Minerva McJanda": "politics_society", "halim alrah": "politics_society",
    "Olivia L.": "politics_society", "Soliloquy": "politics_society",
    "Austin Walker": "gaming", "A More Civilized Age: A Star Wars Podcast": "podcast_actualplay",
    "Sarah Margaret": "politics_society",
    # --- urbanism ---
    "Not Just Bikes": "urbanism_transit", "Car Free Keith": "urbanism_transit",
    "Heartland Urbanist": "urbanism_transit", "Reject Convenience": "urbanism_transit",
    "new practice": "urbanism_transit",
    # --- comedy / sketch / abridged ---
    "Bad Lip Reading": "comedy_sketch", "bill wurtz": "comedy_sketch",
    "boburnham": "comedy_sketch", "KRAZAM": "comedy_sketch",
    "ProZD": "comedy_sketch", "TomSka": "comedy_sketch",
    "TomSka & Friends": "comedy_sketch", "nathanfielder": "comedy_sketch",
    "Vic Berger": "comedy_sketch", "Demi Adejuyigbe": "comedy_sketch",
    "Internet Comment Etiquette with Erik": "comedy_sketch",
    "All Gas No Brakes": "comedy_sketch", "Garfunkel And Oates": "music",
    "alyankovic": "music", "Nice Peter": "music", "SethEverman": "music",
    "Dropout": "comedy_sketch", "RDCworld1": "comedy_sketch",
    "Glove and Boots": "comedy_sketch", "potterpuppetpals": "comedy_sketch",
    "homestarrunnerdotcom": "animation", "charlieissoboredlike": "comedy_sketch",
    "truthorfail": "comedy_sketch", "truthorfailnosub": "comedy_sketch",
    "Bitch Avenue": "comedy_sketch", "Emmy Blotnick": "comedy_sketch",
    "Isabella Roland": "comedy_sketch", "Jordan Myrick": "comedy_sketch",
    "Sailor J": "comedy_sketch", "Jamie Loftus": "comedy_sketch",
    "TheRealBradNeely": "comedy_sketch", "TeamFourStar": "comedy_sketch",
    "KaiserNeko": "comedy_sketch", "Little Kuriboh": "comedy_sketch",
    "GanXingba": "comedy_sketch", "PurpleEyesWTF": "comedy_sketch",
    "Faulerro": "comedy_sketch", "Even Idiots Can Make Anime": "comedy_sketch",
    "HAWPOfficial": "comedy_sketch", "Olivia Griffin": "comedy_sketch",
    "Donald Faison": "comedy_sketch", "Vought International": "comedy_sketch",
    "The SUPERWRESTLERS!": "comedy_sketch", "Table 8 Productions": "comedy_sketch",
    "Do You Validate": "comedy_sketch", "Hyenas and Gin": "comedy_sketch",
    "Trauma Tonight with Harry Dreyfuss AMFT": "comedy_sketch",
    "HangoverUncensored": "comedy_sketch", "Gamblor": "comedy_sketch",
    "Agent Mystery Meat": "comedy_sketch", "Jesse Tribble": "comedy_sketch",
    "sweetDawg": "comedy_sketch", "Kofie": "comedy_sketch",
    "NardwuarServiette": "music", "Barry Kramer ": "gaming",
    "jan Misali": "general_education", "Xidnaf": "general_education",
    "suckerpinch": "programming_tech", "adef": "comedy_sketch",
    "meow": "comedy_sketch", "Cheese Turbulence": "comedy_sketch",
    "MartSnack": "comedy_sketch", "Ballin' Out SUPER": "gaming",
    "Nickolas Nameolas": "comedy_sketch", "Plus2Joe": "comedy_sketch",
    "JeremyThunder": "comedy_sketch", "ichibanhomie": "comedy_sketch",
    "Ray Ramses": "comedy_sketch", "Navek": "comedy_sketch",
    "katbamkapow": "comedy_sketch", "Critical Kate (of A Critical Hit!)": "gaming",
    "Charlotte McDonnell": "comedy_sketch",
    # --- animation / VFX ---
    "TerminalMontage": "animation", "Pegbarians": "animation",
    "SmallButera": "animation", "Doctor Puppet": "animation",
    "Noodle": "animation", "Mattias Pilhede": "animation",
    "IanHubert": "animation", "Zach King": "animation",
    "OneyNG": "animation", "Egoraptor": "animation",
    "Marble Hornets": "video_essay_media", "BravestWarriors": "animation",
    "JelloApocalypse": "animation", "OlanRogers": "comedy_sketch",
    "FlibidyDibidy": "animation", "Boarbarktree": "animation",
    "Pasta Cats": "animation", "Pettyartist": "animation",
    "HatchiMatchi": "animation", "1Kids (Mike)": "animation",
    "Amazing Animation Analysis": "video_essay_media",
    "Even Idiots Can Make Anime ": "comedy_sketch",
    "AnimEigo & Whole Grain Pictures": "animation", "Discotek Media": "animation",
    "FUNimationLive": "animation", "Silver Sprocket": "animation",
    "The Thief and the Cobbler Archive Official": "animation",
    "Ramayana : The Legend Of Prince Rama": "animation",
    "Baahubali Movie": "video_essay_media", "お兄ちゃんねる - OniiChannel": "animation",
    "ナナシ": "animation", "jaytaiko": "animation", "reichhen": "animation",
    "headfallsoff": "animation", "DeepBlueInk": "animation",
    "Alex Boucher": "animation", "GC Vazquez": "animation",
    "Srcerer": "animation", "Micro ": "animation",
    # --- music (proper) ---
    "Louie Zong": "music", "Radical Face": "music", "Lorde": "music",
    "the Mountain Goats": "music", "Nujabes": "music",
    "Smooth McGroove": "music", "Shawn Wasabi": "music", "Lau Noah": "music",
    "Paul E.T.": "music", "Matt Mulholland YouTube": "music",
    "The Blanks Official YouTube Page": "music", "dftbarecords": "music",
    "collectivecadenza": "music", "Shogo Sakai (NekoChill / 酒井省吾 )": "music",
    "James Howell": "music", "WangleLine": "music", "mothcub": "music",
    "Justin Bennett": "music", "soiboi soft": "music", "BluShades": "music",
    "LowercaseJai": "music", "dovsky": "music", "Trace Five": "music",
    "The Sound Traveler": "music", "Radical Face ": "music",
    # --- podcasts / actual play ---
    "The McElroy Family": "podcast_actualplay", "Griffin McElroy": "podcast_actualplay",
    "Justin McElroy": "podcast_actualplay", "Travis McElroy": "podcast_actualplay",
    "Dimension 20": "podcast_actualplay", "Friends at the Table": "podcast_actualplay",
    "Welcome to Night Vale": "podcast_actualplay", "Ranged Touch": "podcast_actualplay",
    "Chris Remo": "gaming", "Let's Talk About Stuff": "podcast_actualplay",
    "Crit Build": "podcast_actualplay", "Brandon Leon-Gambetta": "podcast_actualplay",
    "Will Save Productions": "podcast_actualplay",
    # --- food ---
    "J. Kenji López-Alt": "food", "ProZD Eats Food": "food",
    "GASTROFÍSICA": "food", "H.BurgerGuy": "food", "Amy & Jacky": "food",
    # --- misc individual creators ---
    "Peeja": "programming_tech", "acollieralso": "science",
    "Emily K Sowers": "vlog_personality", "The Cooler Jenny": "vlog_personality",
    "Bijan Stephen": "gaming", "Jenna Stoeber": "gaming",
    "Jasper": "gaming", "Tom Lum": "science", "Greg and Mitch": "science",
    "Holy Fucking Science": "science", "Hot Mess": "science",
    "Afterthoughts": "video_essay_media", "Errant Signal ": "game_design_analysis",
    "The Art Assignment": "video_essay_media", "Ours Poetica": "video_essay_media",
    "Zanzlanz": "gaming", "mklachu": "gaming", "Velodus": "gaming",
    "LuckyChainsaw": "gaming", "DouchebagChocolat": "gaming",
    "Elite3 Backup Channel": "gaming", "DEMOLITIONDv2": "gaming",
    "TheRealJims": "gaming", "EnlargedKai": "gaming", "Clockwork": "gaming",
    "Strangest Quiet": "music", "Stay Inside": "music",
    "Nikki": "vlog_personality", "meow ": "comedy_sketch",
    "Isahowdy": "vlog_personality", "DoeEyes": "vlog_personality",
    "camwing ": "programming_tech", "Kav P": "video_essay_media",
    "Bryan Saint": "video_essay_media", "ReviewCandy": "video_essay_media",
    "ehmteevee": "video_essay_media", "zayloox": "gaming",
    "gone for good": "video_essay_media", "AZFanFam": "vlog_personality",
    "James-Money": "gaming", "Jack": "gaming", "Jeffiot": "gaming",
    "HumZillion": "video_essay_media", "Hilltop": "music",
    "Greyt Show": "comedy_sketch", "Fredrik Knudsen ": "video_essay_media",
    "From Scratch": "programming_tech", "SPEED BOAT DOPE": "comedy_sketch",
    "PlayTheMind": "science", "Frame of Essence": "science",
    "Skull": "unknown", "ShadyVox": "music",
}
